services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - shared_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - shared_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: martech_data
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/docker-entrypoint-initdb.d
    networks:
      - shared_network

networks:
  shared_network:
    external: true